#pragma once
#ifndef __CLOSE_COMBAT_ENEMY_ANIMATION_STATE__
#define __CLOSE_COMBAT_ENEMY_ANIMATION_STATE__

enum class CloseCombatEnemyAnimationState
{
	CLOSE_ENEMY_IDLE,
	CLOSE_ENEMY_RUN_RIGHT,
	CLOSE_ENEMY_RUN_LEFT,
	CLOSE_ENEMY_FIRE,
	NUM_OF_ANIMATION_STATES
};

#endif